import React, { useEffect, useState } from 'react'
import styled from 'styled-components'
import IconButton from '@mui/material/IconButton'
import CloseIcon from '@mui/icons-material/Close'

import { useAppDispatch, useAppSelector } from '../hooks'
import { closeWhiteboardDialog } from '../stores/WhiteboardStore'
import { getWhiteboardOccupants } from '../util/whiteboard'

const Backdrop = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  padding: 16px 16px 16px 16px;
  display: flex;
  gap: 12px;
`

const Wrapper = styled.div`
  flex: 1;
  min-width: 0;
  background: #222639;
  border-radius: 16px;
  padding: 16px;
  color: #eee;
  position: relative;
  display: flex;
  flex-direction: column;

  .close {
    position: absolute;
    top: 0;
    right: 0;
    z-index: 2;
  }
`

const SidePanel = styled.aside`
  width: 220px;
  flex-shrink: 0;
  background: rgba(15, 23, 42, 0.94);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 16px;
  padding: 14px;
  color: #e2e8f0;
  display: flex;
  flex-direction: column;
  gap: 10px;

  h3 {
    margin: 0;
    font-size: 14px;
    font-weight: 700;
    color: #f8fafc;
  }

  p {
    margin: 0;
    font-size: 11px;
    line-height: 1.45;
    color: #94a3b8;
  }
`

const OccupantList = styled.ul`
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
`

const OccupantItem = styled.li`
  font-size: 13px;
  padding: 6px 8px;
  border-radius: 8px;
  background: rgba(51, 65, 85, 0.65);
  color: #f1f5f9;
`

const WhiteboardWrapper = styled.div`
  flex: 1;
  border-radius: 12px;
  overflow: hidden;
  margin-top: 8px;

  iframe {
    width: 100%;
    height: 100%;
    background: #fff;
    border: none;
  }
`

export default function WhiteboardDialog() {
  const whiteboardUrl = useAppSelector((state) => state.whiteboard.whiteboardUrl)
  const whiteboardId = useAppSelector((state) => state.whiteboard.whiteboardId)
  const participants = useAppSelector((state) => state.participants.participants)
  const dispatch = useAppDispatch()
  const [occupants, setOccupants] = useState(() => getWhiteboardOccupants(whiteboardId))

  useEffect(() => {
    const refresh = () => setOccupants(getWhiteboardOccupants(whiteboardId))
    refresh()
    const id = window.setInterval(refresh, 600)
    return () => window.clearInterval(id)
  }, [whiteboardId, participants])

  return (
    <Backdrop>
      <Wrapper>
        <IconButton
          aria-label="close dialog"
          className="close"
          onClick={() => dispatch(closeWhiteboardDialog())}
        >
          <CloseIcon />
        </IconButton>
        {whiteboardUrl ? (
          <WhiteboardWrapper>
            <iframe title="white board" src={whiteboardUrl} allow="clipboard-read; clipboard-write" />
          </WhiteboardWrapper>
        ) : (
          <p style={{ margin: 'auto', opacity: 0.85 }}>Loading whiteboard…</p>
        )}
      </Wrapper>

      <SidePanel>
        <h3>On this board</h3>
        <p>
          Names inside the whiteboard are auto-generated by WBO. Use this list to see who is who in
          SkyOffice.
        </p>
        <OccupantList>
          {occupants.length === 0 ? (
            <OccupantItem>Just you</OccupantItem>
          ) : (
            occupants.map((person) => (
              <OccupantItem key={person.id}>
                {person.name}
                {person.isSelf ? ' (you)' : ''}
              </OccupantItem>
            ))
          )}
        </OccupantList>
      </SidePanel>
    </Backdrop>
  )
}
